package construct

import (
	"io"
	"github.com/a-h/generate"
	"fmt"
)

func Output(writer io.Writer, generatedSchemaMap *generate.Generator) {
	// structs := generatedSchemaMap.Structs
	// aliases := generatedSchemaMap.Alias
	fmt.Printf("%#v", generatedSchemaMap.Structs["On"])

	imports := []string{
		"gopkg.in/yaml.v3",
	} 

	fmt.Fprintln(writer, "// GENERATED CODE. DO NOT EDIT THIS FILE")
	fmt.Fprintln(writer, "package gen_schema")
	fmt.Fprintf(writer, "\n")

	writeImports(writer, imports)
}

func writeImports(writer io.Writer, imports []string) {
	fmt.Fprint(writer, "import (")
	
	for _, importfile := range imports {
		fmt.Fprintf(writer, "\n\t\"%s\"", importfile)
	}
	fmt.Fprintln(writer, "\n)")
}

